### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SoniaP96** [imnotamember/BART-OpenSesame#1]
Hi! I'm trying to use the BART task for OpenSesame, but there's a problem that I'm not able to solve. The task always stops after the practice phase, and a "syntax error" shows up. Unfortunately I'm not able to solve this problem alone, since I don't know anything about Python or other types of programming languages. Is there someone who can help me? Thank you very much!
![Error](https://user-images.githubusercontent.com/98527008/151351877-301510fb-2a78-4da4-8eba-8fe364db765f.png)

**Comment by imnotamember** [comment]
Yikes!

This is a sadly outdated version of the task. I can push an update that will at least get it running again.
The error your seeing is due to the code being written in Python 2 syntax instead of Python 3 syntax, where `print 'this'` must be written as `print('this')`.

Should have this updated by the end of the day.

**Comment by SoniaP96** [comment]
Thank you very much for the explanation and for your help!

**Comment by imnotamember** [comment]
Just pushed a fixed version. Try it out and let me know if you have any issues.

**Comment by imnotamember** [comment]
Hey @SoniaP96 , any updates? I'll close this issue once I hear everything is working on your end.

**Comment by imnotamember** [comment]
I'm going to close this issue as resolved, but if you're still having issues @SoniaP96 don't hesitate to reopen this issue or contact me at joshua.e.zosky@gmail.com!
